### ISSUE TITLE
What to do with the old staff team

### ISSUE THREAD

**Issue by NekoMajo** [HackerExperience/Community#2]
The old staff team containing:
- NekoMajo
- DodySpy
- LegendaryPhil

Still care about the HE1 community and are not a part of this new structure, We have done a ton for this community with the lack of help from above, and would not be happy to be shut out after all the work we have put in to help shape this community in to what it is.

**Comment by renatomassaro** [comment]
> and are not a part of this new structure

That's not necessarily true. As outlined on [CTF](https://github.com/HackerExperience/Community/blob/master/CTF.md), we have management positions open to all teams, including CM, and I personally would like to have the three of you as part of this new community, but I cannot force your participation in any way.

I'm open to discuss ways we can all work together to keep improving the community and the game. Just ping me on Discord.

**Comment by DUFC-Liam** [comment]
They are still apart of the team to my knowledge due to them being on a non-maintained project they are not shown to be main's in those positions.
